

export const Nfts = [
    {
        id:1,
        image:'https://i.seadn.io/gcs/files/d98ce9834799e8b417ad8cc27b90f33f.png?auto=format&w=256',
        name:"Owls",
        userName:"REI-N",
        floor:"0.17",
        volume:"1581",
        description:"10'000 owls. Randomly generated on-chain from over 90'000'000 possible combinations.",
        dateCreated:"Mar 2023",
        items:"9999",
        chain:"Ethereum",
        category:"PFPs",
        url:"https://opensea.io/collection/owls-wtf",
        unit:"ETH",
        website:"https://www.owls.wtf/"
    },
    {
        id:2,
        image:'https://i.seadn.io/gcs/files/ea3c15935f9142ecb0a8d20398281841.png?auto=format&w=256',
        name:"Momoguro: Holoself",
        userName:" Holoself-Deployer",
        floor:"0.33",
        volume:"8946",
        description:"Discovering Momoguro starts with an 8,888 collection of the Holoself Avatars, the key to exploring the Uno Plane. From 9x Emmy-winning animation & storytelling studio, Baobab Studios, Momoguro is a new multimedia franchise and narrative RPG where you collect and fuse with creatures to unravel the secrets of Momoguro. Join us in Discord & on Twitter!",
        dateCreated:"Mar 2023",
        items:"8888",
        chain:"Ethereum",
        category:"",
        url:"https://opensea.io/collection/owls-wtf",
        unit:"ETH",
        website:"https://momoguro.com/"
    },
    {
        id:3,
        image:'https://i.seadn.io/gcs/files/866691c691d0426769120db411b57e86.png?auto=format&w=256',
        name:"Pudgy Rods",
        userName:"TheIglooCompany",
        floor:"0.6878 ",
        volume:"5221",
        description:"It's rog season baby 🎣. Wen utility?",
        dateCreated:"Aug 2021 ",
        items:"7394",
        chain:"Ethereum",
        category:"Art",
        url:"https://opensea.io/collection/pudgyrods",
        unit:"ETH",
        website:"https://pudgypenguins.com/"
    },
    {
        id:4,
        image:'https://i.seadn.io/gcs/files/1a97c71426c4da6f8f679d6e2b4491a3.gif?auto=format&w=256',
        name:"SchizoPosters",
        userName:"",
        floor:"0.3069",
        volume:"603",
        description:"I HATE THE ANTICHRIST I HATE THE ANTICHRIST I HATE THE ANTICHRIST I HATE THE ANTICHRIST I HATE THE ANTICHRIST I",
        dateCreated:"Mar 2023",
        items:"5555",
        chain:"Ethereum",
        category:"Art",
        url:"https://opensea.io/collection/schizoposters",
        unit:"ETH",
        website:"https://schizoposters.xyz/"
    },
    {
        id:5,
        image:'https://i.seadn.io/gae/0Y5-78kylODBsl1E8mL6iU6pZJXZcfkIEJaQk4q4R_b6Fc7a0bKZv4pN51I4_PeRN5AQKdHrQesSLceZ5e5V5r1TmkkWKbnjMuqhwQ?auto=format&w=256',
        name:"Citizens of Bulliever Island",
        userName:"Bullieverse",
        floor:"0.079",
        volume:"1386",
        description:"Welcome to Bullieverse, where you can play various games built on unreal engine solo, with friends, and against others in PvP to win incredible prizes and NFT rewards. The Citizens of Bulliever Island are the Genesis collection of 10,000 fully unique, playable game avatars and the original inhabitants of Bulliever Island. These NFTs have a ton of utility, like exclusive access to special promotions, game tournaments, and the entire Bullieverse game economy. Our second game, Necrodemic, is available now and ready for you to play!",
        dateCreated:"Aug 2021",
        items:"8888",
        chain:"Ethereum",
        category:"",
        url:"https://opensea.io/collection/owls-wtf",
        unit:"Gaming",
        website:"https://bullieverse.com/"
    },
    {
        id:6,
        image:'https://i.seadn.io/gcs/files/a1cb29951fb8d87a9ba6bbb955543db6.png?auto=format&w=256',
        name:"Vintage Vibes",
        userName:"",
        floor:"0.0002",
        volume:"8",
        description:"Vintage Vibes is an NFT collection of 3333 unique characters in a retro cartoon style",
        dateCreated:"Mar 2023",
        items:"3333",
        chain:"Ethereum",
        category:"Art",
        url:"https://opensea.io/collection/vintagevibesnft",
        unit:"ETH",
        website:"https://www.vintagevibesnft.xyz/"
    },
    {
        id:7,
        image:'https://i.seadn.io/gcs/files/ea3c15935f9142ecb0a8d20398281841.png?auto=format&w=256',
        name:"Momoguro: Holoself",
        userName:" Holoself-Deployer",
        floor:"0.33",
        volume:"8946",
        description:"Discovering Momoguro starts with an 8,888 collection of the Holoself Avatars, the key to exploring the Uno Plane. From 9x Emmy-winning animation & storytelling studio, Baobab Studios, Momoguro is a new multimedia franchise and narrative RPG where you collect and fuse with creatures to unravel the secrets of Momoguro. Join us in Discord & on Twitter!",
        dateCreated:"Mar 2023",
        items:"8888",
        chain:"Ethereum",
        category:"",
        url:"https://opensea.io/collection/owls-wtf",
        unit:"ETH",
        website:"https://momoguro.com/"
    },
    {
        id:8,
        image:'https://i.seadn.io/gcs/files/ea3c15935f9142ecb0a8d20398281841.png?auto=format&w=256',
        name:"Momoguro: Holoself",
        userName:" Holoself-Deployer",
        floor:"0.33",
        volume:"8946",
        description:"Discovering Momoguro starts with an 8,888 collection of the Holoself Avatars, the key to exploring the Uno Plane. From 9x Emmy-winning animation & storytelling studio, Baobab Studios, Momoguro is a new multimedia franchise and narrative RPG where you collect and fuse with creatures to unravel the secrets of Momoguro. Join us in Discord & on Twitter!",
        dateCreated:"Mar 2023",
        items:"8888",
        chain:"Ethereum",
        category:"",
        url:"https://opensea.io/collection/owls-wtf",
        unit:"ETH",
        website:"https://momoguro.com/"
    },
    {
        id:9,
        image:'https://i.seadn.io/gcs/files/ea3c15935f9142ecb0a8d20398281841.png?auto=format&w=256',
        name:"Momoguro: Holoself",
        userName:" Holoself-Deployer",
        floor:"0.33",
        volume:"8946",
        description:"Discovering Momoguro starts with an 8,888 collection of the Holoself Avatars, the key to exploring the Uno Plane. From 9x Emmy-winning animation & storytelling studio, Baobab Studios, Momoguro is a new multimedia franchise and narrative RPG where you collect and fuse with creatures to unravel the secrets of Momoguro. Join us in Discord & on Twitter!",
        dateCreated:"Mar 2023",
        items:"8888",
        chain:"Ethereum",
        category:"",
        url:"https://opensea.io/collection/owls-wtf",
        unit:"ETH",
        website:"https://momoguro.com/"
    }
]